spring:
  datasource:
    driver-class-name: 'org.h2.Driver'
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    name: testdb
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
springdoc:
  api-docs:
    enabled: true
#    path: "api-docs"
  swagger-ui:
    enabled: true
#    path: "/swagger"